// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zdplqsdeyubdplmlaqhu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpkcGxxc2RleXViZHBsbWxhcWh1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNzg2NTgsImV4cCI6MjA2Mzk1NDY1OH0.Fo0G4X7yFCdpjKv0e6XPTm0keYVl0w4-ec9WznUS3Zs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);